const SkillNameByID = {
  0: "1H Blunt",
  1: "1H Slashing",
  2: "2H Blunt",
  3: "2H Slashing",
  4: "Abjuration",
  5: "Alteration",
  6: "Apply Poison",
  7: "Archery",
  8: "Backstab",
  9: "Bind Wound",
  10: "Bash",
  11: "Block",
  12: "Brass Instruments",
  13: "Channeling",
  14: "Conjuration",
  15: "Defense",
  16: "Disarm",
  17: "Disarm Traps",
  18: "Divination",
  19: "Dodge",
  20: "Double Attack",
  21: "Dragon Punch",
  22: "Dual Wield",
  23: "Eagle Strike",
  24: "Evocation",
  25: "Feign Death",
  26: "Flying Kick",
  27: "Forage",
  28: "Hand To Hand",
  29: "Hide",
  30: "Kick",
  31: "Meditate",
  32: "Mend",
  33: "Offense",
  34: "Parry",
  35: "Pick Lock",
  36: "Piercing",
  37: "Riposte",
  38: "Round Kick",
  39: "Safe Fall",
  40: "Sense Heading",
  41: "Singing",
  42: "Sneak",
  43: "Specialize Abjure",
  44: "Specialize Alteration",
  45: "Specialize Conjuration",
  46: "Specialize Divination",
  47: "Specialize Evocation",
  48: "Pick Pockets",
  49: "Stringed Instruments",
  50: "Swimming",
  51: "Throwing",
  52: "Tiger Claw",
  53: "Tracking",
  54: "Wind Instruments",
  55: "Fishing",
  56: "Make Poison",
  57: "Tinkering",
  58: "Research",
  59: "Alchemy",
  60: "Baking",
  61: "Tailoring",
  62: "Sense Traps",
  63: "Blacksmithing",
  64: "Fletching",
  65: "Brewing",
  66: "Alcohol Tolerance",
  67: "Begging",
  68: "Jewelry Making",
  69: "Pottery",
  70: "Percussion Instruments",
  71: "Intimidation",
  72: "Berserking",
  73: "Taunt ",
  74: "Frenzy",
  75: "Remove Traps",
  76: "Triple Attack",
  77: "2H Piercing"
};

const SkillIDByName = {
  "1H Blunt": 0,
  "1H Slashing": 1,
  "2H Blunt": 2,
  "2H Slashing": 3,
  "Abjuration": 4,
  "Alteration": 5,
  "Apply Poison": 6,
  "Archery": 7,
  "Backstab": 8,
  "Bind Wound": 9,
  "Bash": 10,
  "Block": 11,
  "Brass Instruments": 12,
  "Channeling": 13,
  "Conjuration": 14,
  "Defense": 15,
  "Disarm": 16,
  "Disarm Traps": 17,
  "Divination": 18,
  "Dodge": 19,
  "Double Attack": 20,
  "Dragon Punch": 21,
  "Dual Wield": 22,
  "Eagle Strike": 23,
  "Evocation": 24,
  "Feign Death": 25,
  "Flying Kick": 26,
  "Forage": 27,
  "Hand To Hand": 28,
  "Hide": 29,
  "Kick": 30,
  "Meditate": 31,
  "Mend": 32,
  "Offense": 33,
  "Parry": 34,
  "Pick Lock": 35,
  "Piercing": 36,
  "Riposte": 37,
  "Round Kick": 38,
  "Safe Fall": 39,
  "Sense Heading": 40,
  "Singing": 41,
  "Sneak": 42,
  "Specialize Abjure": 43,
  "Specialize Alteration": 44,
  "Specialize Conjuration": 45,
  "Specialize Divination": 46,
  "Specialize Evocation": 47,
  "Pick Pockets": 48,
  "Stringed Instruments": 49,
  "Swimming": 50,
  "Throwing": 51,
  "Tiger Claw": 52,
  "Tracking": 53,
  "Wind Instruments": 54,
  "Fishing": 55,
  "Make Poison": 56,
  "Tinkering": 57,
  "Research": 58,
  "Alchemy": 59,
  "Baking": 60,
  "Tailoring": 61,
  "Sense Traps": 62,
  "Blacksmithing": 63,
  "Fletching": 64,
  "Brewing": 65,
  "Alcohol Tolerance": 66,
  "Begging": 67,
  "Jewelry Making": 68,
  "Pottery": 69,
  "Percussion Instruments": 70,
  "Intimidation": 71,
  "Berserking": 72,
  "Taunt ": 73,
  "Frenzy": 74,
  "Remove Traps": 75,
  "Triple Attack": 76,
  "2H Piercing": 77
}

module.exports = {
  SkillNameByID,
  SkillIDByName
}